import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Date, Document } from 'mongoose';
import { Comment, CommentSchema } from './comment.schema';

@Schema()
export class Pattern extends Document {
  @Prop({ required: true })
  type: string;

  @Prop({ required: true })
  websiteId: string;

  @Prop({ required: true })
  isAutoGenerated: boolean;

  @Prop()
  expertId: string;

  @Prop()
  description: string;

  @Prop()
  detectedUrl: string;

  @Prop({ type: [CommentSchema] })
  comments: Comment[];

  @Prop({ default: Date.now, type: Date })
  createdAt: Date;
}

export const PatternSchema = SchemaFactory.createForClass(Pattern);
