import { CommentResponseDto } from './comment-response.dto';

export class PatternResponseDto {
  type: string;
  websiteId: string;
  isAutoGenerated: boolean;
  expertId: string;
  expertName: string;
  description: string;
  detectedUrl: string;
  comments: CommentResponseDto[];
}
