import { Date } from 'mongoose';
import { CommentResponseDto } from './comment-response.dto';
import { Verification } from '../schemas/pattern.schema';

export class PatternResponseDto {
  id: string;
  patternType: string;
  websiteId: string;
  isAutoGenerated: boolean;
  createdByExpertId: string;
  expertName: string;
  description: string;
  detectedUrl: string;
  createdAt: Date;
  patternPhase: string;
  isPatternExists: boolean;
  comments: CommentResponseDto[];
  expertVerifications: Verification[];
}
