import React, {useState} from 'react'

interface PatternCardProps {
    patternKey: any; 
    isAutoGenerated: boolean; 
    loggedInExpert: string; 
    pattern_date: string; 
    pattern_type: string;
    expertName: string; 
    color: string; 
    text: string; 
    hoverText: string; 
    openModal: () => void; 
  }

const PatternCard: React.FC<PatternCardProps> = ({patternKey , isAutoGenerated, loggedInExpert, pattern_date, pattern_type, expertName, color, text, hoverText, openModal}) => {
    console.log(patternKey, loggedInExpert);
    const autoTag = isAutoGenerated ? 'Automatic' : "Manual"
    let name = loggedInExpert === patternKey ? 'You' : expertName 
    const inputDate = new Date(pattern_date);
    const options: Intl.DateTimeFormatOptions = { year: 'numeric', month: 'long', day: 'numeric' };
    const formattedDate: string = inputDate.toLocaleDateString('en-US', options);
    const [elemText, setElemText] = useState(text);
    const handleHoverText = () => {
        setElemText(hoverText);
    };
    const handleMouseLeave = () => {
        setElemText(text);
    };
    const getBorderColorClass = color==="blue" ? "border-blue-300" : color==="green" ? "border-green-300" : "border-red-300" 
    const getTextColorClass = color==="blue" ? "text-blue-500" : color==="green" ? "text-green-500" : "text-red-500" ;
    const getBgColorClass = color==="#F9C32F" ? "bg-[#F9C32F]" : color==="#E6321D" ? "bg-[#E6321D]" : "bg-[#538D3F]" ;
    const getButtonBgClass =  color==="blue" ? "bg-blue-300" : color==="green" ? "bg-green-300" : "bg-red-300" ;
    const autoTagColor = autoTag ==="Automatic" ? "bg-[#ED6762]" : autoTag ==="Manual" ? "bg-[#631158]" : null
  return (
    <div className={`md:col-span-1 shadow-xl py-1 rounded-xl bg-white mt-4 `} key={patternKey}>
        <div className='flex justify-between mt-2'>
          <h1 className={`py-1 px-3 text-xl`}>{pattern_type}</h1>
          <div className='flex'>
          <div className={`flex items-center mx-3 px-3 rounded-2xl ${getBgColorClass}`} onMouseOver={handleHoverText} onMouseLeave={handleMouseLeave}>
            <p className={`text-white`}>{elemText}</p>
          </div>
          </div>
        </div>
        <div className='flex justify-between my-2'>
        <div className={`flex items-center mx-3 px-3 rounded-2xl bg-[#DCC3F4]`}>
            <p className={`text-white`}>{autoTag}</p>
          </div>
          <p className='text-gray-400 px-3 italic font-serif '>Created By : {name}</p>
        </div>
        <div className='flex justify-between py-1 px-3 my-2'>
          <button className={`px-8 py-1 bg-gradient-to-r from-cyan-500 to-blue-500 rounded-lg shadow-lg text-white`} onClick={openModal}>View Details</button>
          <p className='italic font-serif text-gray-400'>{formattedDate}</p>
        </div>
    </div>
  )
}

export default PatternCard