import React from "react";

export interface Reply {
    expertId : string;
    expertName : string;
    content : string;
    createdAt : string;
  }
export interface Comment {
    id: string,
    websiteId: string,
    patternId: string,
    expertId: string,
    expertName: string,
    content: string,
    createdAt: string,
    replies: Reply[]; 
  }
  
export interface verification {
    expertId: string;
    expertVerificationPhase: string
  }
export interface PatternData {
      comments : Comment[];
      createdAt : string;
      createdByExpertId : string;
      description : string;
      detectedUrl : string;
      expertName: string;
      expertVerifications : verification[];
      id : string;
      isAutoGenerated : boolean;
      patternType: string;
      patternPhase: string;
      websiteId : string;
}
export interface PatternDetailsProps {
    isOpen: boolean;
    onClose: () => void;
    expertId : string;
    token : string
}